// Code generated by mockery v2.27.1. DO NOT EDIT.

package metrics

import mock "github.com/stretchr/testify/mock"

// MockMetrics is an autogenerated mock type for the Metrics type
type MockMetrics struct {
	mock.Mock
}

type MockMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetrics) EXPECT() *MockMetrics_Expecter {
	return &MockMetrics_Expecter{mock: &_m.Mock}
}

// GetThroughput provides a mock function with given fields:
func (_m *MockMetrics) GetThroughput() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockMetrics_GetThroughput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetThroughput'
type MockMetrics_GetThroughput_Call struct {
	*mock.Call
}

// GetThroughput is a helper method to define mock.On call
func (_e *MockMetrics_Expecter) GetThroughput() *MockMetrics_GetThroughput_Call {
	return &MockMetrics_GetThroughput_Call{Call: _e.mock.On("GetThroughput")}
}

func (_c *MockMetrics_GetThroughput_Call) Run(run func()) *MockMetrics_GetThroughput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetrics_GetThroughput_Call) Return(_a0 uint64) *MockMetrics_GetThroughput_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetrics_GetThroughput_Call) RunAndReturn(run func() uint64) *MockMetrics_GetThroughput_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementThroughput provides a mock function with given fields:
func (_m *MockMetrics) IncrementThroughput() {
	_m.Called()
}

// MockMetrics_IncrementThroughput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementThroughput'
type MockMetrics_IncrementThroughput_Call struct {
	*mock.Call
}

// IncrementThroughput is a helper method to define mock.On call
func (_e *MockMetrics_Expecter) IncrementThroughput() *MockMetrics_IncrementThroughput_Call {
	return &MockMetrics_IncrementThroughput_Call{Call: _e.mock.On("IncrementThroughput")}
}

func (_c *MockMetrics_IncrementThroughput_Call) Run(run func()) *MockMetrics_IncrementThroughput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetrics_IncrementThroughput_Call) Return() *MockMetrics_IncrementThroughput_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetrics_IncrementThroughput_Call) RunAndReturn(run func()) *MockMetrics_IncrementThroughput_Call {
	_c.Call.Return(run)
	return _c
}

// SendMetrics provides a mock function with given fields:
func (_m *MockMetrics) SendMetrics() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetrics_SendMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMetrics'
type MockMetrics_SendMetrics_Call struct {
	*mock.Call
}

// SendMetrics is a helper method to define mock.On call
func (_e *MockMetrics_Expecter) SendMetrics() *MockMetrics_SendMetrics_Call {
	return &MockMetrics_SendMetrics_Call{Call: _e.mock.On("SendMetrics")}
}

func (_c *MockMetrics_SendMetrics_Call) Run(run func()) *MockMetrics_SendMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetrics_SendMetrics_Call) Return(_a0 error) *MockMetrics_SendMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetrics_SendMetrics_Call) RunAndReturn(run func() error) *MockMetrics_SendMetrics_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockMetrics interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMetrics creates a new instance of MockMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMetrics(t mockConstructorTestingTNewMockMetrics) *MockMetrics {
	mock := &MockMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
